backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Name", name: "name", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Commercial", "Personal & Academic"] }
      - { label: "Status", name: "status", widget: "select", options: ["active", "suspended", "finished"] }
      - { label: "Technologies (manual entry)", name: "technologies", widget: "list" }
      - { label: "Duration", name: "duration", widget: "string", required: false }
      - { label: "GitHub Repository URL", name: "url", widget: "string", required: false }
      - { label: "README Content", name: "body", widget: "markdown" }