# Bare-bones config for debugging
backend:
  name: test-repo

# We need at least one collection for the CMS to load
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }